steps:
    - id: "Go test"
          name: "gcr.io/cloud-builders/go"
          args: [ "test" ]
          env: [ "GOPATH=." ]

    -   id: "Building image from Dockerfile"
        name: 'gcr.io/cloud-builders/docker'
        args: ['build','-t','gcr.io/$PROJECT_ID/go-greeting:$SHORT_SHA','-f','Dockerfile.prod','.']

    -   id: "Pushing image"
        name: 'gcr.io/cloud-builders/docker'
        args: ['push','gcr.io/$PROJECT_ID/go-greeting:$SHORT_SHA']

    -   id: 'Adjusting deployment file - k8s'
        name: 'gcr.io/cloud-builders/gcloud'
        entrypoint: '/bin/sh'
        args:
            - '-c'
            - |
                sed 's#img-app-deployment#gcr.io/$PROJECT_ID/go-greeting:$SHORT_SHA#g' k8s/app/deployment.yaml > k8s/app/deployment-new.yaml;
                cat k8s/app/deployment-new.yaml;

    -   id: 'Deploying k8s'
        name: 'gcr.io/cloud-builders/kubectl'
        args:
            - 'apply'
            - '-f'
            - 'k8s/app/deployment-new.yaml'
        env:
            - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
            - 'CLOUDSDK_CONTAINER_CLUSTER=my-first-cluster-1'
