apiVersion: v1
kind: ConfigMap
metadata:
    name: nginx-conf
data:
    nginx.conf: |
        server {
            listen 80;
            location / {
                return 200 "Code.education Rocks";
                add_header Content-Type text/plain;
            }
        }